# prefs.ini is the sole settings file. Import engine defaults from config.spec.
file(STRINGS "${CMAKE_SOURCE_DIR}/config/config.spec" SPEC_LINES ENCODING UTF-8)
file(READ "${CMAKE_SOURCE_DIR}/config/prefs.ini" DEFAULT_INI)
set(CHARACTERS "\n[english_pronunciation]\n")
set(ENGLISH "\n[english_letters]\n")
set(RUSSIAN "\n[russian_letters]\n")
set(LETTER_SYMBOLS "")
set(SECTION "")
foreach(LINE IN LISTS SPEC_LINES)
 if(LINE MATCHES "^\\[(.*)\\]$")
  set(SECTION "${CMAKE_MATCH_1}")
 elseif(LINE MATCHES "^([^#=]+) = [a-z]+\\(.*default=([^)]*)\\)$")
  set(KEY "${CMAKE_MATCH_1}")
  set(VALUE "${CMAKE_MATCH_2}")
  if(SECTION STREQUAL "Parameters")
   if(KEY STREQUAL "samples_per_sec")
    # SAPI gets the core audio unchanged, so this rate is also the output rate.
    # The bridge ships with the top of the slider: the rate of the original
    # Newfon SAPI, which its JAWS instructions name.
    set(KEY "sample_rate")
    set(VALUE "11025")
   endif()
   string(APPEND DEFAULT_INI "${KEY} = ${VALUE}\n")
  elseif(SECTION STREQUAL "Characters")
   # [english_pronunciation] is "Latin combinations" and holds Latin only;
   # other letters become always-on entries of [symbols].
   if(KEY MATCHES "^[a-z]+$")
    string(APPEND CHARACTERS "${KEY} = ${VALUE}\n")
   else()
    list(APPEND LETTER_SYMBOLS "${KEY}|${VALUE}")
   endif()
  elseif(SECTION STREQUAL "SingleCharacters")
   if(KEY MATCHES "^[a-z]$")
    string(APPEND ENGLISH "${KEY} = ${VALUE}\n")
   else()
    string(APPEND RUSSIAN "${KEY} = ${VALUE}\n")
   endif()
  endif()
 endif()
endforeach()
file(READ "${CMAKE_SOURCE_DIR}/config/symbols.ini" SYMBOLS)
string(STRIP "${SYMBOLS}" SYMBOLS)
string(APPEND SYMBOLS "\n")
# Entries already present in symbols.ini win.
foreach(ITEM IN LISTS LETTER_SYMBOLS)
 string(REGEX MATCH "^([^|]+)\\|(.*)$" _ "${ITEM}")
 string(FIND "${SYMBOLS}" "\n${CMAKE_MATCH_1} = " FOUND)
 if(FOUND EQUAL -1)
  string(APPEND SYMBOLS "${CMAKE_MATCH_1} = ${CMAKE_MATCH_2}:1\n")
 endif()
endforeach()
string(APPEND DEFAULT_INI "${CHARACTERS}${ENGLISH}${RUSSIAN}\n${SYMBOLS}")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
file(WRITE "${CMAKE_BINARY_DIR}/bin/prefs.ini" "${DEFAULT_INI}")
configure_file(src/config/Defaults.h.in "${CMAKE_BINARY_DIR}/generated/Defaults.h" @ONLY)
target_include_directories(newfon_config PRIVATE "${CMAKE_BINARY_DIR}/generated")
